version: '3.4'


services:
  mvcweb:
    image: ${DOCKER_REGISTRY-}mvcweb
    build:
      context: .
      dockerfile: MvcWeb/Dockerfile
    ports:
      - 443:443


  wapi:
    image: ${DOCKER_REGISTRY-}wapi
    build:
      context: .
      dockerfile: wApi/Dockerfile
    ports:
      - 443:443

  sqldb:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "tvxs721#3"
      ACCEPT_EULA: "Y"