apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: wapi
  name: wapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: wapi
    spec:
      containers:
      - image: wapi
        imagePullPolicy: ""
        name: wapi
        ports:
        - containerPort: 443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
